name: Datura
main: me.totalfreedom.datura.Datura
version: 1.0.0
author: TotalFreedom
description: Data Manager for the Freedom Network Suite
libraries:
  - com.discord4j:discord4j-core:3.2.3
  - com.discord4j:discord4j-commons:3.2.3